site_name: My Django Docs
nav:
  - Home: index.md
  - Model Layer:
    - model_layer/index.md
    - Model: 
      - model_layer/model/index.md
      - Making Queries:
        - model_layer/model/making_queries.md
        - Queryset API: api/queryset_api/queryset_api.md
      - Model instance reference: model/model_inst_ref.md
      
  - Django REST API:
    - rest_api/index.md




  - About: about.md

theme:
  name: material
  features:
    - navigation.tracking
    - navigation.indexes
    - navigation.expand
    - pymdownx.superfences
    - pymdownx.betterem
    - pymdownx.extra
    - pymdownx.highlight
    # - toc.integrate

  palette:
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets

plugins:
  - section-index